### ISSUE TITLE
Use the exporter without devtools open?

### ISSUE THREAD

**Issue by soulgalore** [devtools-html/har-export-trigger#13]
Hi Jan,
if I use latest nightly, should the exporter work without opening devtools (I cannot get it to work) or do the plugin need any changes or is it anything else that needs to land before it to work in Firefox?

Best
Peter

**Comment by xmhubj** [comment]
see here 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Extending_the_developer_tools

HAR Export trigger addon has a devtools page, which is loaded when the browser devtools are opened. Looks like it requires devtools open to load the page.

**Comment by soulgalore** [comment]
@xmhubj see https://github.com/devtools-html/har-export-trigger/issues/8#issuecomment-368887624

**Comment by janodvarko** [comment]
@soulgalore Yes, @xmhubj is right. The Devtools Toolbox must be opened. But, the Network panel doesn't have to be explicitly selected (this support is implemented in Firefox 61).

In fact, it's better if the Network panel is *not* selected, so its UI doesn't have to be updated during the page load (perf improvement).

Honza

**Comment by soulgalore** [comment]
Ah cool thanks for the clarification!

**Comment by soulgalore** [comment]
Actually I tried now with FF 61 beta5 and if I skip setting `profile.setPreference('devtools.toolbox.selectedTool', 'netmonitor');` it doesn't work (at least for me).

Also do you know @janodvarko if there's a way to disable the popup that happens when you open devtools?
<img width="514" alt="screen shot 2018-05-17 at 09 39 26" src="https://user-images.githubusercontent.com/540757/40163286-b38b92c0-59b6-11e8-9840-50cb4796391a.png">

**Comment by janodvarko** [comment]
There are two related prefs:

`devtools.devedition.promo.shown` and `devtools.devedition.promo.enabled`

https://searchfox.org/mozilla-central/rev/d4b9e50875ad7e5d20f2fee6a53418315f6dfcc0/devtools/client/preferences/devtools-client.js#5-14

It should be enough to set `devtools.devedition.promo.enabled` to `false`

> Actually I tried now with FF 61 beta5 and if I skip setting
> profile.setPreference('devtools.toolbox.selectedTool', 'netmonitor'); it doesn't work (at least for me).

This sounds like similar issue to the one we are solving in: https://github.com/devtools-html/har-export-trigger/issues/8

The backend is *not* collecting HTTP data unless:
1) The Network panel is selected
2) An extension expresses an interest in the data. This means that one of the two APIs are executed: either `getHAR`  or registering a listener for `onRequestFinished`.

It's related to performance,  the backend should not collect the data all the time - only if needed.

I understand that this complicates the usage a bit, but not sure if there is a better solution...

Can you try that?

Honza

**Comment by soulgalore** [comment]
Ah cool, np, I will try it today/tomorrow when I find the tlme! Thanks again for all the help!

**Comment by farooqrahman** [comment]
I tried testing the har-exporter without explicitly selecting the network panel but I have opened the devtools toolbox. For the first page, I got empty entries in the HAR and for the later pages, it works fine. (entries object populated with values)

When I explicitly selected the network panel then for the first page I got entries object populated with values. 

It seems that there is some problem with the first page by not selecting the network panel.

Regards,
Farooq.

**Comment by janodvarko** [comment]
> I tried testing the har-exporter without explicitly selecting the network panel but I have opened the devtools toolbox. For the first page, I got empty entries in the HAR and for the later pages, it works fine. (entries object populated with values)

@farooqrahman this should be fixed in the latest version  (0.6.1) on AMO.
(since issue #16 is fixed)

Honza

**Comment by janodvarko** [comment]
Btw. the promo popup window displayed when the Toolbox is opened for the first time should be removed in Firefox 62

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1463924

Honza

**Comment by motin** [comment]
> @soulgalore Yes, @xmhubj is right. The Devtools Toolbox must be opened. But, the Network panel doesn't have to be explicitly selected (this support is implemented in Firefox 61).

Is this still valid if we run privileged code using https://wiki.mozilla.org/WebExtensions/Experiments?

**Comment by janodvarko** [comment]
> Is this still valid if we run privileged code using https://wiki.mozilla.org/WebExtensions/Experiments?

Just for the record. I had a meeting with @motin in SF last week and the goal here is to build an extension that is able to:

* create its own debugger client object
* connect to Firefox backend
* initialize NetMonitorAPI object
* Load page & record HTTP activity
* Export HAR

Some code notes:

```js
// framework/toolbox-init.js
DebuggerServer.init();
const client = new DebuggerClient();
await client.connect();
const tab = await client.getTab();

// framework/toolbox.js
const netAPI = Toolbox.getNetMonitorAPI();
const hart = getHARFromNetMonitor();

// netmonitor/src/api.js
NetMonitorAPI.connectBackend();
```

@motin it would be great if you linked your results here in this thread, so others can benefit from that work and continue building on top.

Honza

**Comment by motin** [comment]
@janodvarko I had a stab at this today and seemingly got many things running:
 * Create debugger client object
 * Connect to Firefox backend (kind of, see below)
 * Initialize NetMonitorAPI object
 * Export HAR (kind of, see below)

Code here: https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4

These major issues are still unresolved:
* Connect to Firefox backend - I can't pick out the corresponding tab from the WebExtension. Querying client.listTabs() gives me the remote protocol version of the tab list, but the list from browser.tabs.query({}) is rather different than the one from the debuggerserver, with no overlapping identifiers / indices. As a temporary workaround I am simply grabbing the second tab in the list, so that it connects to the second tab I open during a testing session.
* Load page & record HTTP activity - The HTTP activity does not seem to be recorded anywhere. The HAR returned from NetMonitor is always null
* Export HAR - Because of the above, the exported HAR is always the empty HAR from `buildHarLog(Services.appinfo)`

Pointers and advice welcome, since I don't see where this is faulting. :)

**Comment by ochameau** [comment]
I think I'm lost at WebExtension layer.
It is not clear from where `enableNetworkMonitorForTab` is called and what is the `tabId` argument being passed to it? There must be a way in WebExtension to pass a Tab object of WebExtension and from it, retrieve the real Firefox tab, that we use in DevTools.

@rpl Do you know if that's possible to implement a WebExtension experiment with an API accepting a tab parameter? (I imagine that what is called TabBase, right?) And then, within the experiment implementation, is it possible to get the `tab` object, the firefox one, the `<xul:tab>` element? If not, would it be possible to get the current `outerWindowID` of the tab, or the `tabId` (the tabParent.tabId one, https://searchfox.org/mozilla-central/source/dom/interfaces/base/nsITabParent.idl#62).

**Comment by motin** [comment]
> (I imagine that what is called TabBase, right?)

Thanks @ochameau, with that class hint as guidance, I found a way to map WebExtension tabId -> the debugger's version of the tab object by querying tabManager directly, followed by querying the debugger server based on the nativeTab object: https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4/commits/0fb646f3e94d3a4a0a18f429a97f3fe65d65079d

The major unresolved issue now is that the HTTP activity does not seem to be recorded anywhere. [The HAR returned from NetMonitor](https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4/files#diff-439ac9b25774debd4b6bb1d37b23c55fR104) is always null. Source code for the connection to NetMonitor: https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4/files#r206454224

**Comment by rpl** [comment]
> @rpl Do you know if that's possible to implement a WebExtension experiment with an API accepting a tab parameter?

I didn't had the time to look into the experiment implementation yet, but from inside an API implementation you can retrieve the native tab (that is a `<xul:tab>` on Firefox Desktop) from a WebExtension `tabId` using the `tabTracker` utility (and an instance of it is already available in the global where the API module runs, and so it can be used without importing anything explicitly):

```js
const nativeTab = tabTracker.getTab(tabId)
```
([tabTracker.getTab implementation for Firefox Desktop](https://searchfox.org/mozilla-central/rev/033d45ca70ff32acf04286244644d19308c359d5/browser/components/extensions/parent/ext-browser.js#359-380), [tabTracker.getTab(tabId) usage from other API modules](https://searchfox.org/mozilla-central/search?q=tabTracker.getTab&path=))

Once the API implementation has got the native tab object, it can create a devtools connection to it by using something like: ```DevToolsShim.createTargetForTab(tab)```.

**Comment by motin** [comment]
Thanks @rpl, the tab issue has been resolved for now. Your comment allowed the code to be [cleaned up a bit](https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4/commits/798f1c3fb5c1e77f2c34d8ae31d109e3a58d6604) (except for the tabTracker part, since tabTracker is not defined globally, nor available as extension.tabTracker - so I am [sticking to extension.tabManager](https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4/files#diff-a14244cdec5f8d917359647726400210R43) for now). 

However, even when using DevToolsShim to create the target, the network monitoring doesn't start. The exported HAR is always empty. Copying from https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4#pullrequestreview-141867474:

> motin an hour ago  Collaborator
> HTTP activity does not seem to be recorded anywhere. The HAR returned from NetMonitor is always null. What is missing here?
> 
>   @ochameau
> ochameau an hour ago  Member
> It will only start recording from here, when calling this.getNetMonitorAPI().connect.
> So you will have to reload the current page or load a new one in the tab in order to get some data out of NetMonitorAPI.getHar() (and wait for the end of load).
> 
>   @motin
> motin an hour ago  Collaborator
> It doesn't seem to work currently. I can reload the page twenty times, write new URLs in the address bar of the monitored tab etc after this statement - without anything but empty HAR contents being returned by NetMonitor afterwards.
> 
>   @ochameau
> ochameau an hour ago  Member
> Hum. I don't know then.
> 
> It would be helpful to trace what is happening here:
> https://searchfox.org/mozilla-central/source/devtools/client/netmonitor/src/api.js#107
> options.items should be a non empty array.
> 
> Then ensure that this code is trigerred:
> https://searchfox.org/mozilla-central/source/devtools/client/netmonitor/src/connector/firefox-connector.js#71
> Without the call to addListeners here, nothing will be recorded.
> 
> Finally, you could also ensure the redux actions are correctly dispatched for each request, from here:
> https://searchfox.org/mozilla-central/source/devtools/client/netmonitor/src/connector/firefox-data-provider.js#76-77
> Otherwise, the store won't be populated.
> 
> If all that is correct, then I'm really out of clue.

I have inspected the source code and arguments sent to these methods without finding anything yet that is incorrect. Just prior to HAR export, `netMonitor.store.getState().requests.requests` is always an empty Map, resulting in options.items being an empty array, so it definitely seems like no requests are being stored in the state to begin with. 

Next, I'll trace/debug the netmonitor source code during runtime (to ensure that addListeners is being called and redux actions are dispatched) via the Browser Toolbox.

**Comment by ochameau** [comment]
May be Honza will have some idea as he wrote the HAR code, but he is on PTO. He will be back next week.

> Next, I'll trace/debug the netmonitor source code during runtime (to ensure that addListeners is being called and redux actions are dispatched) via the Browser Toolbox.

Yes, no need to build Firefox. You can debug all DevTools codebase from nightly. All the Frontend codebase should be debuggable from the Browser toolbox. Note that the actor codebase (code from devtools/server/) doesn't appear in the Browser toolbox, but in the Browser content toolbox. This may be harder to debug.

**Comment by motin** [comment]
@ochameau Indeed, debugging via the Browser Toolbox works great :)
Found a likely culprit: It seems like all listeners are indeed setup for a brief time after a new tab is created, but the target is being destroyed and all listeners subsequently unregistered following onTabDetached in https://searchfox.org/mozilla-central/source/devtools/client/framework/target.js#533, which fires just before navigation. Thus, there are never any requests available to export since about:newtab makes no requests. Also, this.getNetMonitorAPI().connect takes some time to finish, and the tab continues to load in the background, resulting in missed initial requests. Then, as soon as I try to navigate somewhere, all listeners for the tab are torn down. Subsequent attempts to reload the page / navigate somewhere are then fruitless since there are no listeners active (event the tabTarget object is gone, self-destructed, so no events on it can be subscribed to).

It seems that the initial set up of devtools listeners needs to be done somewhere else than upon tab created / tab updated events in WebExtension land, but instead in some tabManager/tabTracker/tabTarget event callback, preferably in a way that ensures that the page does not load until the listeners are setup - Ideas on how/where to do that?

**Comment by rpl** [comment]
> Thanks @rpl, the tab issue has been resolved for now. Your comment allowed the code to be cleaned up a bit (except for the tabTracker part, since tabTracker is not defined globally, nor available as extension.tabTracker - so I am sticking to extension.tabManager for now).

Using extension.tabManager is also absolutely fine, and internally it still uses [tabTracker.getTab](https://searchfox.org/mozilla-central/rev/033d45ca70ff32acf04286244644d19308c359d5/browser/components/extensions/parent/ext-browser.js#1018-1025).

But instead of using `tabManager.query` to retrieve all the tabs and then filter the one that you are interested in (like in the code you linked in your previous comment), it would be better and easier to use `tabManager.get(tabId)` to get only the "Tab wrapper" you are interested in, and then from it you can get the native tab from its `nativeTab` property, as in the following snippet:

```
var tab = extension.tabManager.get(tabId);
var devtoolsTarget = DevToolsShim.createTargetForTab(tab.nativeTab);
```

**Comment by motin** [comment]
@rpl, thanks, that again lead to [cleaner code](https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4/commits/291315049b5e6e13f211187125dd82c49a8d97f9). Any idea of how to actually achieve complete and persistent network monitoring for the tabs?

**Comment by janodvarko** [comment]
> Found a likely culprit: It seems like all listeners are indeed setup for a brief time after a new tab is created, but the target is being destroyed and all listeners subsequently unregistered following onTabDetached in https://searchfox.org/mozilla-central/source/devtools/client/framework/target.js#533, which fires just before 

I can reproduce this too.

The DebuggerServer is sending "tabDetached" packet 
https://searchfox.org/mozilla-central/rev/721842eed881c7fcdccb9ec0fe79e4e6d4e46604/devtools/server/main.js#1078

This happens since "message-manager-close" event is fired and this event is send since the browser tab is removed in `updateBrowserRemoteness`:
https://searchfox.org/mozilla-central/rev/721842eed881c7fcdccb9ec0fe79e4e6d4e46604/browser/base/content/tabbrowser.js#1597

`updateBrowserRemoteness`is called by SessionRestore

Here is my callstack:

DebuggerServer.connectToFrame send 'tabDetached' main.js:1078:11
connectToFrame/</destroy< resource://devtools/server/main.js:1079:11
exports.makeInfallible/< resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
onMessageManagerClose resource://devtools/server/main.js:1101:11
updateBrowserRemoteness chrome://browser/content/tabbrowser.js:1597:5
restoreTabContent resource:///modules/sessionstore/SessionStore.jsm:3997:9
restoreTab resource:///modules/sessionstore/SessionStore.jsm:3911:9
navigateAndRestore/< resource:///modules/sessionstore/SessionStore.jsm:3064:7

@ochameau is this an expected behavior? Can we somehow avoid that?

Honza

**Comment by motin** [comment]
Including a copy of @rpl's comment from https://github.com/mozilla/OpenWPM-WebExtension-Experiment/pull/4#issuecomment-417690456 here as well, so that all relevant insights are collected in the same thread:

> @motin I took another look at this, to check what may still be missing from the code that initialize the network monitor API component, and I guess that it may be related at least to the following:
> 
> - the "NetworkActivity" listener has to be started on the console actor to make it able to emit the "networkEvent" RDP events (which, if I'm not wrong, are the once that are collected by the Netmonitor API and then converted into the HAR logs), e.g. it seems that we do something similar here:
>   https://searchfox.org/mozilla-central/rev/05d91d3e02a0780f44599371005591d7988e2809/devtools/client/netmonitor/initializer.js#80-83
>   and so my guess is that in the experiment API it has to be done near here: https://github.com/mozilla/OpenWPM-WebExtension-Experiment/blob/626fcbbe0fab1111de8590dd3cf7951a43f84682/src/api.js/Monitor.js#L104
>   by adding something like:
>   ```js
>     await target.makeRemote();
>     await target.activeConsole.startListeners(["NetworkActivity"]);
>     await netMonitor.connect(MockToolbox);
>   ```
> 
> - it seems to me that all the collected requests are cleared by default when the target tab navigates if "devtools.netmonitor.persistlog" preference is not true, which (at least from what I see) it is happening from here: https://searchfox.org/mozilla-central/rev/05d91d3e02a0780f44599371005591d7988e2809/devtools/client/netmonitor/src/connector/firefox-connector.js#171-174, to avoid the requests to be cleared on navigation we may need to make it configurable per "NetMonitor API" instance, which will likely require some changes in mozilla-central first (e.g. optionally allow to pass a parameter to the connect method, something like `await netMonitor.connect(MockToolbox, {persistLog: true});`)
> 
> @janodvarko what do you think about the above two comments? may they be the reasons for the empty HAR archive?

**Comment by janodvarko** [comment]
> @janodvarko what do you think about the above two comments? may they be the reasons for the empty HAR archive?

Both comments make sense and yes not starting the network listeners seems like a bug.
But I am still puzzled why DebuggerServer is sending the "tabDetached" packet...

Honza

**Comment by motin** [comment]
Thanks for looking into this further. I took your comments and tried anew without any luck.

EDIT: I found some network monitoring happening at some stage. Updated the answer below to reflect this:

It seems that 1. attaching to the tab objects needs to be done at a deeper level, something like upon any creation of a tab/browser object everywhere, and 2. there is still something missing in terms of keeping the instrumentation alive.

**1. Attaching the debugger server to the tab objects at the right moment**
@janodvarko It seems that updateBrowserRemoteness is called as part of Firefox moving the tab URI loading into a separate process. Apparently, when a new tab is created (in the UI), the tab object for `about:blank` is created in the same process as the previous tab, but subsequently moved to a separate process upon navigation to another URL (with SessionRestore doing the actual destroying the previous tab process and "restoring" it into a new process). 

Thus, the problem with the initial approach (attaching the debugger to the tab on create) is thus that the tab object available at the time of onCreate event sent to the web extension API gets destroyed when Firefox moves the tab browser into a new process, without a new onCreate tab event being sent to the web extension API.

Does anyone know of any such event that can be consumed, so that the debugger can be attached properly before the web page starts loading?

**2. Keeping the instrumentation alive**
I enabled monitoring on the onUpdated event (when status=loading) and set `devtools.netmonitor.persistlog` to be always true (via web-ext), as well as added
```
  await target.makeRemote();
  await target.activeConsole.startListeners(["NetworkActivity"]);
```
as per @rpl's comment. 

Now, there are occasionally some requests in the store before the HAR export is triggered but the HAR export fails with `Error: "Error while calling method getEventTimings: No such actor for ID: server1.conn0.netEvent1862"`. Screenshot with the browser log at this moment: [[https://www.dropbox.com/s/6je211fksldqml2/Screenshot%202018-09-10%2019.47.05.png?dl=1]]

Also, just like before, the error `TypeError: "getTabTarget(...) is null"` is still encountered, and no requests are recorded for instance on a visit to https://www.independent.co.uk/ - There *should* be network activity monitored in this case since the network monitoring should have attached on the tab onUpdated, status=loading, event. Still empty HAR logs.

**Comment by motin** [comment]
Quick update: We went another way, using the instrumentation exposed via the standard web extension API:s instead. This allows access to basic request monitoring and performance metrics, but not any ability to debug / analyze scripts, create memory dumps, performance profiles etc - thus still interested in having remote access to Devtools without having to have Devtools open, but not actively pursuing it at the moment.

**Comment by xiaospider** [comment]
@motin can you share how you using the instrumentation exposed via the standard web extension API:s instead?
